name: Build Migrator

on:
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.202'

    - name: Publish Migrator
      run: dotnet publish ./src/Host/l7TeamVN.SaaS.Migrator/l7TeamVN.SaaS.Migrator.csproj -c Release -o C:\Deployments\Migrator\SaaS

    - name: Update Config
      uses: microsoft/variable-substitution@v1
      with:
        files: 'C:\Deployments\Migrator\appsettings.json'
      env:
        Modules.Identity.ConnectionStrings.Default: ${{ secrets.PROD_CONNECTION_STRING }}